#!/usr/bin/env python3
"""
MAFIA Phase 2: Final Policy Learning (Gold Dataset)

This script trains a fresh TD3 Allocator on the "Gold Dataset" of Vintage States 
generated by Phase 1 (Data Factory).

Strategy (per training_strategy_proposal.md):
1. Load Accumulated Vintage States (rl_state_2020.pt, rl_state_2021.pt, etc.)
2. Load corresponding Market Data (OCHLV) for Reward Calculation.
3. Create 'VintageStateEnv' - A simple Gym environment that:
   - Yields PRE-COMPUTED states (Vintage States) as observations.
   - Calculates rewards based on actual price returns.
4. Train TD3 on the Training Split (e.g., 2020-2023).
5. Validate on the Validation Split (e.g., 2024).
"""

import os
import sys
import torch as th
import numpy as np
import pandas as pd
import argparse
import gym
from gym import spaces
from typing import Dict, List, Tuple, Optional

# Ensure repo root on sys.path
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, os.pardir))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)

from config import Config
from utils.mafia_data_loader import load_mafia_data

try:
    from stable_baselines3 import TD3
    from stable_baselines3.common.noise import NormalActionNoise
except ImportError:
    print("stable_baselines3 not found. Install with: pip install stable-baselines3")
    sys.exit(1)

try:
    from utils.display_integration import smart_print
except ImportError:
    smart_print = print


class VintageStateEnv(gym.Env):
    """
    Simple Gym environment for TD3 training on Vintage States.
    
    Observation: Pre-computed state from Observer (embeddings + topk_embeddings).
    Action: Portfolio weights for top-K stocks.
    Reward: Portfolio return based on actual price changes.
    """
    
    def __init__(
        self,
        vintage_states: Dict[str, th.Tensor],
        price_returns: np.ndarray,  # (T, N) daily returns
        stock_dates: List[str],      # Dates for price data
        top_k: int = 10,
        embedding_dim: int = 128,
        transaction_cost: float = 0.001,
    ):
        super().__init__()
        
        self.vintage_states = vintage_states
        self.price_returns = price_returns
        self.stock_dates = stock_dates
        self.transaction_cost = transaction_cost
        
        # Auto-detect dimensions from vintage states
        # embeddings: (T, D), top_k_embeddings: (T, K, D)
        self.D = vintage_states["embeddings"].shape[1]
        self.top_k = vintage_states["top_k_embeddings"].shape[1]

        
        # Normalize date formats to ISO strings (YYYY-MM-DD)
        def normalize_date(d):
            """Convert various date types to YYYY-MM-DD string."""
            if isinstance(d, str):
                return d[:10]  # Truncate if has time
            elif hasattr(d, 'strftime'):  # pandas.Timestamp
                return d.strftime('%Y-%m-%d')
            elif hasattr(d, 'astype'):  # numpy.datetime64
                return str(d)[:10]
            else:
                return str(d)[:10]
        
        vintage_dates_normalized = [normalize_date(d) for d in vintage_states["dates"]]
        price_dates_normalized = [normalize_date(d) for d in stock_dates]
        
        # Map vintage dates to indices
        self.date_to_vintage_idx = {d: i for i, d in enumerate(vintage_dates_normalized)}
        self.date_to_price_idx = {d: i for i, d in enumerate(price_dates_normalized)}
        
        # Find overlapping dates
        self.valid_dates = [d for d in vintage_dates_normalized if d in self.date_to_price_idx]
        self.num_steps = len(self.valid_dates) - 1  # -1 for terminal state

        
        if self.num_steps <= 0:
            raise ValueError(f"No overlapping dates between vintage states and price data!")
        
        smart_print(f"[VintageStateEnv] {len(self.valid_dates)} valid dates, {self.num_steps} steps")
        
        # Observation space: [global_emb(D) + topk_emb(K*D) + risk_eta(1)]
        obs_dim = self.D + self.top_k * self.D + 1
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(obs_dim,), dtype=np.float32
        )
        
        # Action space: Portfolio weights for top-K stocks
        self.action_space = spaces.Box(
            low=0.0, high=1.0, shape=(self.top_k,), dtype=np.float32
        )
        
        self.current_step = 0
        self.prev_weights = np.ones(self.top_k) / self.top_k  # Equal weights initially
        
    def _get_observation(self) -> np.ndarray:
        """Get observation for current step."""
        date = self.valid_dates[self.current_step]
        idx = self.date_to_vintage_idx[date]
        
        # Global embedding (D,)
        global_emb = self.vintage_states["embeddings"][idx].numpy()
        
        # Top-K embeddings (K, D) -> flatten to (K*D,)
        topk_emb = self.vintage_states["top_k_embeddings"][idx].numpy().flatten()
        
        # Risk eta (1,)
        risk_eta = self.vintage_states["risk_eta"][idx].numpy().flatten()
        
        # Concatenate
        obs = np.concatenate([global_emb, topk_emb, risk_eta]).astype(np.float32)
        return obs
    
    def _get_topk_indices(self) -> np.ndarray:
        """Get top-K stock indices for current step."""
        date = self.valid_dates[self.current_step]
        idx = self.date_to_vintage_idx[date]
        return self.vintage_states["top_k_indices"][idx].numpy().astype(int)
    
    def reset(self) -> np.ndarray:
        self.current_step = 0
        self.prev_weights = np.ones(self.top_k) / self.top_k
        return self._get_observation()
    
    def step(self, action: np.ndarray) -> Tuple[np.ndarray, float, bool, dict]:
        """
        Execute one step.
        
        Args:
            action: Portfolio weights for top-K stocks (K,)
            
        Returns:
            obs: Next observation
            reward: Portfolio return
            done: Episode finished
            info: Additional info
        """
        # Normalize action to sum to 1
        weights = np.clip(action, 0.0, 1.0)
        weights = weights / (weights.sum() + 1e-8)
        
        # Get current and next date
        current_date = self.valid_dates[self.current_step]
        next_date = self.valid_dates[self.current_step + 1]
        
        # Get top-K indices and corresponding returns
        topk_idx = self._get_topk_indices()
        price_idx = self.date_to_price_idx.get(next_date)
        
        if price_idx is None or price_idx >= len(self.price_returns):
            # No return data available
            reward = 0.0
        else:
            # Get returns for top-K stocks
            topk_returns = self.price_returns[price_idx, topk_idx]
            
            # Portfolio return = weighted sum
            portfolio_return = np.sum(weights * topk_returns)
            
            # Transaction cost (turnover penalty)
            turnover = np.abs(weights - self.prev_weights).sum() / 2
            cost = turnover * self.transaction_cost
            
            reward = portfolio_return - cost
        
        # Update state
        self.prev_weights = weights
        self.current_step += 1
        
        # Check done
        done = self.current_step >= self.num_steps
        
        # Get next observation
        if not done:
            obs = self._get_observation()
        else:
            obs = np.zeros(self.observation_space.shape, dtype=np.float32)
        
        info = {
            "date": current_date,
            "topk_indices": topk_idx.tolist(),
            "weights": weights.tolist(),
        }
        
        return obs, reward, done, info


def load_gold_dataset(data_dir: str, years: List[int]) -> Optional[Dict]:
    """Load and concatenate vintage states."""
    combined = {
        "embeddings": [],
        "top_k_indices": [],
        "top_k_embeddings": [],
        "risk_eta": [],
        "dates": []
    }
    
    for year in years:
        path = os.path.join(data_dir, f"rl_state_{year}.pt")
        if not os.path.exists(path):
            print(f"[Warning] Missing vintage state for {year} at {path}")
            continue
            
        print(f"Loading {path}...")
        state = th.load(path, map_location="cpu", weights_only=False)
        
        combined["embeddings"].append(state["embeddings"])
        combined["top_k_indices"].append(state["top_k_indices"])
        if "top_k_embeddings" in state:
            combined["top_k_embeddings"].append(state["top_k_embeddings"])
        else:
            print(f"Warning: top_k_embeddings missing in {path}!")
            return None
            
        combined["risk_eta"].append(state["risk_eta"])
        combined["dates"].extend(state["dates"])
    
    if len(combined["embeddings"]) == 0:
        return None
        
    # Concat
    return {
        "embeddings": th.cat(combined["embeddings"], dim=0),
        "top_k_indices": th.cat(combined["top_k_indices"], dim=0),
        "top_k_embeddings": th.cat(combined["top_k_embeddings"], dim=0),
        "risk_eta": th.cat(combined["risk_eta"], dim=0),
        "dates": combined["dates"]
    }


def load_price_returns(config: Config) -> Tuple[np.ndarray, List[str], List[str]]:
    """Load price data and compute daily returns."""
    raw_data = load_mafia_data(config)
    
    # Pivot to (dates, stocks)
    dates = sorted(raw_data["date"].unique())
    stocks = sorted(raw_data["stock"].unique())
    
    pivot = raw_data.pivot(index="date", columns="stock", values="close")
    pivot = pivot.fillna(method="ffill").fillna(method="bfill")
    
    # Compute returns
    returns = pivot.pct_change().fillna(0.0).values  # (T, N)
    
    date_strs = [str(d) for d in dates]
    
    return returns, date_strs, stocks


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--train-years", nargs="+", type=int, default=[2020, 2021, 2022, 2023])
    parser.add_argument("--valid-years", nargs="+", type=int, default=[2024])
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()
    
    # 1. Config
    config = Config()
    
    # Paths
    vintage_dir = os.path.join(REPO_ROOT, "res", "walkforward_yearly")
    
    # 2. Load Gold Dataset
    print(f"Loading Gold Dataset Train: {args.train_years}, Valid: {args.valid_years}")
    
    train_states = load_gold_dataset(vintage_dir, args.train_years)
    if train_states is None:
        print("No training data found! Run Phase 1 first.")
        return
    
    valid_states = load_gold_dataset(vintage_dir, args.valid_years)
    if valid_states is None:
        print("No validation data found! Using training data for validation in dry-run.")
        valid_states = train_states
    
    # 3. Load Price Data
    all_years = args.train_years + (args.valid_years if valid_states else [])
    min_year, max_year = min(all_years), max(all_years)
    config.train_date_start = f"{min_year}-01-01"
    config.train_date_end = f"{max_year}-12-31"
    
    print("Loading Price Data...")
    returns, dates, stocks = load_price_returns(config)
    print(f"Loaded returns: {returns.shape} (dates, stocks)")
    
    # 4. Get config values
    top_k = getattr(config, "mafia_top_k", 10)
    D = getattr(config, "mafia_D", 128)
    
    # 5. Create Environments
    print("Creating VintageStateEnvs...")
    
    env_train = VintageStateEnv(
        vintage_states=train_states,
        price_returns=returns,
        stock_dates=dates,
        top_k=top_k,
        embedding_dim=D,
    )
    
    env_valid = VintageStateEnv(
        vintage_states=valid_states,
        price_returns=returns,
        stock_dates=dates,
        top_k=top_k,
        embedding_dim=D,
    )
    
    # 6. Initialize TD3
    print("Initializing TD3 Allocator...")
    n_actions = env_train.action_space.shape[0]
    action_noise = NormalActionNoise(
        mean=np.zeros(n_actions),
        sigma=0.1 * np.ones(n_actions)
    )
    
    model = TD3(
        "MlpPolicy",
        env_train,
        action_noise=action_noise,
        learning_rate=3e-4,
        buffer_size=100000,
        learning_starts=100,
        batch_size=100,
        verbose=1,
    )
    
    # 7. Train
    total_timesteps = 500 if args.dry_run else 50000
    print(f"Starting Training for {total_timesteps} timesteps...")
    
    model.learn(total_timesteps=total_timesteps)
    
    # 8. Validation
    print("Running Validation...")
    obs = env_valid.reset()
    done = False
    total_reward = 0.0
    step_count = 0
    
    while not done:
        action, _ = model.predict(obs, deterministic=True)
        obs, reward, done, info = env_valid.step(action)
        total_reward += reward
        step_count += 1
    
    print(f"Validation Complete: {step_count} steps, Total Reward: {total_reward:.4f}")
    print(f"Avg Daily Return: {total_reward/step_count*100:.4f}%")
    
    print("\n✅ Phase 2 Dry-Run Complete!")


if __name__ == "__main__":
    main()
